name: SootRenamer
version: '${project.version}'
main: net.sootmc.sootrenamer.SootRenamer
api-version: 1.19
authors: [ JamieIsGeek, jaapie_aapie ]
description: A plugin to rename items using commands while still taking XP - Designed for SootMC SMP's
website: play.sootmc.net

commands:
  rename:
    description: Rename an item
    usage: /<command> <name>

permissions:
  sootrenamer.magic:
    description: Permission to allow players to use the magic formatting (&k)
