name: SootRenamer
version: '${project.version}'
main: net.sootmc.sootrenamer.SootRenamer
api-version: 1.19
authors: [ JamieIsGeek ]
description: A plugin to rename items using commands while still taking XP - Designed for SootMC SMP's
website: sootmc.net
